// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/main.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tile_map.dart';

class Board {
  final TileMap map;
  final Pos start;
  final Pos end;
  final Pos resetPos;
  final Direction startDirection;
  final Direction endDirection;

  const Board({
    required this.map,
    required this.start,
    required this.end,
    required this.resetPos,
    required this.startDirection,
    required this.endDirection,
  });

  @override
  int get hashCode =>
      map.hashCode ^
      start.hashCode ^
      end.hashCode ^
      resetPos.hashCode ^
      startDirection.hashCode ^
      endDirection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Board &&
          runtimeType == other.runtimeType &&
          map == other.map &&
          start == other.start &&
          end == other.end &&
          resetPos == other.resetPos &&
          startDirection == other.startDirection &&
          endDirection == other.endDirection;
}
