// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/main.dart';
import '../frb_generated.dart';
import 'board.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'solver.dart';
import 'tile_map.dart';

class Creature {
  final Board board;
  final double fitness;
  final Analysis analysis;
  final BigInt mutationCount;

  const Creature({
    required this.board,
    required this.fitness,
    required this.analysis,
    required this.mutationCount,
  });

  @override
  int get hashCode =>
      board.hashCode ^
      fitness.hashCode ^
      analysis.hashCode ^
      mutationCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Creature &&
          runtimeType == other.runtimeType &&
          board == other.board &&
          fitness == other.fitness &&
          analysis == other.analysis &&
          mutationCount == other.mutationCount;
}
