// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/main.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Analysis {
  final List<(Direction, Pos)> solution;
  final List<Pos> decisionPositions;
  final Int64List moveSizes;

  const Analysis({
    required this.solution,
    required this.decisionPositions,
    required this.moveSizes,
  });

  @override
  int get hashCode =>
      solution.hashCode ^ decisionPositions.hashCode ^ moveSizes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Analysis &&
          runtimeType == other.runtimeType &&
          solution == other.solution &&
          decisionPositions == other.decisionPositions &&
          moveSizes == other.moveSizes;
}
