import 'package:icedash/src/rust/api/main.dart';

final easy = [
  BoardDescription(
    sizeRangeMin: 11,
    sizeRangeMax: 14,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 3,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 10,
    sizeRangeMax: 13,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 3,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 9,
    sizeRangeMax: 12,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 0,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 8,
    sizeRangeMax: 11,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 0,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 7,
    sizeRangeMax: 10,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 0,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
];
