import 'package:icedash/src/rust/api/main.dart';

final extreme = [
  BoardDescription(
    sizeRangeMin: 25,
    sizeRangeMax: 30,
    weakWallsPercentageMin: 10,
    weakWallsPercentageMax: 5,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 25,
    sizeRangeMax: 30,
    weakWallsPercentageMin: 5,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 25,
    sizeRangeMax: 30,
    weakWallsPercentageMin: 5,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 25,
    sizeRangeMax: 30,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 30,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 30,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 25,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 25,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 25,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 25,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 25,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 25,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 10,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
];
