import 'package:icedash/src/rust/api/main.dart';

final extreme = [
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 25,
    weakWallsPercentageMin: 10,
    weakWallsPercentageMax: 5,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 15,
    sizeRangeMax: 20,
    weakWallsPercentageMin: 5,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 15,
    sizeRangeMax: 20,
    weakWallsPercentageMin: 5,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 15,
    sizeRangeMax: 20,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 12,
    sizeRangeMax: 20,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 5,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 12,
    sizeRangeMax: 17,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 0,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 12,
    sizeRangeMax: 15,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 0,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 12,
    sizeRangeMax: 14,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 0,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 11,
    sizeRangeMax: 13,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 0,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 25,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 10,
    pilarsPercentageMax: 30,
    boxPercentageMin: 0,
    boxPercentageMax: 0,
    vignetPercentageMin: 20,
    vignetPercentageMax: 30,
  ),
];
