import 'package:icedash/src/rust/api/main.dart';

final hard = [
  BoardDescription(
    sizeRangeMin: 25,
    sizeRangeMax: 30,
    weakWallsPercentageMin: 10,
    weakWallsPercentageMax: 5,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 22,
    sizeRangeMax: 27,
    weakWallsPercentageMin: 5,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 20,
    sizeRangeMax: 25,
    weakWallsPercentageMin: 5,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 20,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 17,
    sizeRangeMax: 23,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 17,
    sizeRangeMax: 23,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 17,
    sizeRangeMax: 23,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 15,
    sizeRangeMax: 23,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 15,
    sizeRangeMax: 22,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 15,
    sizeRangeMax: 22,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 0,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 15,
    sizeRangeMax: 22,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 15,
    sizeRangeMax: 21,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
  BoardDescription(
    sizeRangeMin: 15,
    sizeRangeMax: 20,
    weakWallsPercentageMin: 0,
    weakWallsPercentageMax: 0,
    pilarsPercentageMin: 5,
    pilarsPercentageMax: 10,
    boxPercentageMin: 0,
    boxPercentageMax: 10,
    vignetPercentageMin: 15,     vignetPercentageMax: 20,
  ),
];
